services:
  factorio-server:
    image: ghcr.io/pvlkrc/factorio-server:latest
    platform: linux/amd64
    tty: true
    stdin_open: true
    container_name: factorio_server
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
      - "34196:34196/udp"
    volumes:
      - ./server-settings.json:/factorio/factorio/data/server-settings.json:ro
      - ./mod-list.json:/factorio/factorio/mods/mod-list.json:ro
      - ./saves:/factorio/factorio/saves