name: Deploy factorio server
on: [push]

jobs:
  BuildAndPushContainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: CheckOut
        uses: actions/checkout@v5
        
      - name: Dockerfile
        run: |
          docker build -t ci_factorio .

      - name: Docker run
        run: |
          docker run -d --name factorio --rm ci_factorio

      - name: Wait for server to start
        run: |
          i=1
          while [ $i -ne 12 ]; do
            if ss -uln | grep -q ":34197 " && docker logs factorio 2>&1 | grep -q "Factorio initialised"; then
              break
            else
              sleep 5; i=$(($i + 1))
            fi
          done
          docker rm -f factorio
          if [ $i = 12 ]; then exit 1; fi

      - name: Push to GitHub Container Registry
        run: |
          VERSION=$(cat VERSION)
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag ci_factorio ghcr.io/${{ github.repository_owner }}/factorio-server:latest
          docker tag ci_factorio ghcr.io/${{ github.repository_owner }}/factorio-server:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/factorio-server:$VERSION
          docker push ghcr.io/${{ github.repository_owner }}/factorio-server:latest